---
output: github_document
always_allow_html: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# jofou.lib

<!-- badges: start -->
<!-- badges: end -->

The goal of `jofou.lib` is to regroup all the functions that are useful for me to work efficiently.

## Installation

You can install the released version of hr.churn from [CRAN](https://CRAN.R-project.org) with:

``` r
devtools::install_github("jofou/jofou.lib")
```

## Example

This are basics examples which shows you how use the my_inspect group function:

```{r example_1, message = F}
library(tidyverse)
library(jofou.lib)

iris %>% 
  my_inspect_cat()
```

```{r example_2, message = F}
library(tidyverse)
library(jofou.lib)

iris %>% 
  my_inspect_cor()
```

```{r example_3, message = F}
library(tidyverse)
library(jofou.lib)

iris %>% 
  my_inspect_imb()
``` 

```{r example_4, message = F}
library(tidyverse)
library(jofou.lib)

iris %>% 
  my_inspect_na()
```

```{r example_5, message = F}
library(tidyverse)
library(jofou.lib)

iris %>% 
  my_inspect_num()
```

```{r example_6, message = F}
library(tidyverse)
library(jofou.lib)

iris %>% 
  my_inspect_types()
```
